### ISSUE TITLE
docker will not start

### ISSUE THREAD

**Issue by airdogvan** [ParisNeo/lollms-webui#319] opened 2023-07-08 18:41 UTC
Log:

docker compose up
[+] Running 1/0
 ⠿ Container lollms-webui-webui-1  Created                                                                                                                                                                    0.0s
Attaching to lollms-webui-webui-1
lollms-webui-webui-1  | Welcome! It seems this is your first use of the new lollms app.
lollms-webui-webui-1  | To make it clear where your data are stored, we now give the user the choice where to put its data.
lollms-webui-webui-1  | This allows you to mutualize models which are heavy, between multiple lollms compatible apps.
lollms-webui-webui-1  | You can change this at any tome using the lollms-settings script or by simply change the content of the global_paths_cfg.yaml file.
lollms-webui-webui-1  | Please provide a folder to store your configurations files, your models and your personal data (database, custom personalities etc).
lollms-webui-webui-1  | Folder path: (/root/Documents/lollms):Traceback (most recent call last):
lollms-webui-webui-1  |   File "/srv/app.py", line 1381, in <module>
lollms-webui-webui-1  |     lollms_paths = LollmsPaths.find_paths(force_local=True, custom_default_cfg_path="configs/config.yaml")
lollms-webui-webui-1  |   File "/usr/local/lib/python3.10/site-packages/lollms/paths.py", line 200, in find_paths
lollms-webui-webui-1  |     cfg.lollms_personal_path = input(f"Folder path: ({cfg.lollms_personal_path}):")
lollms-webui-webui-1  | EOFError: EOF when reading a line
lollms-webui-webui-1 exited with code 1

On Ubuntu 22 LTS

**Comment by airdogvan** [comment] 2023-07-10 16:35
meaning not supported?

**Comment by ParisNeo** [comment] 2023-07-13 06:44
Hi. I think the problem is the interactive parts of the code. I'll try to figure out a way. For now, the new install scripts seem to work fine.
https://youtu.be/OKoXTHXgY28

**Comment by airdogvan** [comment] 2023-07-13 17:04
nice, but the problem with this approach is that it "contaminates" the host you install it on.  By that I mean the script installs lots of stuff that not only might not be needed for other things but also might get in the way (such as the latest version of python for example).
That's why I definitively would prefer to use docker which keeps everything nicely compartmentalized.  My computer runs a lot of stuff,
I might try this on a VM but then no way to use cuda...
Thanks for the feedback anyway, much appreciated...

**Comment by ParisNeo** [comment] 2023-07-14 10:26
The v3 uses a conda based install that keeps all libraries in the same folder and doesn't contaminate your local python install or local conda install.

**Comment by airdogvan** [comment] 2023-07-14 16:45
thank you for the feedback, much appreciated!!!!

no luck so far, I seem to have ownership problems, probably because I used root (seeing on the video that the script installed lots of stuff)  to install which caused problems when I tried to run as normal user.  From what you're writing I assume root is not needed?

Anyway let me try a fresh install (in VM again) and I'll let you know.

**Comment by airdogvan** [comment] 2023-07-14 18:09
ok fresh install in VM Ubuntu 22.  Too long to paste so I include attachment. 
[xxx.txt](https://github.com/ParisNeo/lollms-webui/files/12052854/xxx.txt)

**Comment by ParisNeo** [comment] 2023-07-14 23:24
You never want to install anything as root. Besides this tool was created to be safely installable even if you have no sudo or root privileges whatsoever.  The new installation script is self contained. if you are under linux use linux_install.sh and it should install all you need.
As of docket, I need to remove interactivity for it to work.

**Comment by zba** [comment] 2023-07-22 22:09
i found simple workaround, just run it using
```docker compose run```
instead of "up" but Docker not usable out of the box, for sure, for example configurator ask to keep data in /root/Documents/lollms but, compose not configured to mount this directory, so all data placed there will be lost

**Comment by aospan** [comment] 2023-07-23 12:53
Duplicate of #300

**Closed** 2023-07-30 22:14 UTC
